/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Controlador;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marti Huerta Climent
 */
public class JMain extends javax.swing.JFrame {
    private Controlador control;
    /**
     * Creates new form JMain
     */
    public JMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuWorker = new javax.swing.JMenu();
        menuAddWorker = new javax.swing.JMenuItem();
        menuEditWorker = new javax.swing.JMenuItem();
        menuClient = new javax.swing.JMenu();
        menuAddClient = new javax.swing.JMenuItem();
        menuEditClient = new javax.swing.JMenuItem();
        menuService = new javax.swing.JMenu();
        menuAddService = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuSave = new javax.swing.JMenuItem();
        menuLoad = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cangurs");

        jMenu1.setText("File");

        menuWorker.setText("Worker");

        menuAddWorker.setText("Add Worker");
        menuAddWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddWorkerActionPerformed(evt);
            }
        });
        menuWorker.add(menuAddWorker);

        menuEditWorker.setText("Edit Worker");
        menuEditWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditWorkerActionPerformed(evt);
            }
        });
        menuWorker.add(menuEditWorker);

        jMenu1.add(menuWorker);

        menuClient.setText("Client");

        menuAddClient.setText("Add Client");
        menuAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddClientActionPerformed(evt);
            }
        });
        menuClient.add(menuAddClient);

        menuEditClient.setText("Edit Client");
        menuEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditClientActionPerformed(evt);
            }
        });
        menuClient.add(menuEditClient);

        jMenu1.add(menuClient);

        menuService.setText("Service");

        menuAddService.setText("Add Service");
        menuAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddServiceActionPerformed(evt);
            }
        });
        menuService.add(menuAddService);

        jMenu1.add(menuService);

        jMenuBar1.add(jMenu1);

        menuEdit.setText("Edit");

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setText("Save");
        menuEdit.add(menuSave);

        menuLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuLoad.setText("Load");
        menuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoadActionPerformed(evt);
            }
        });
        menuEdit.add(menuLoad);

        jMenuBar1.add(menuEdit);

        menuAbout.setText("About");

        menuInfo.setText("Info");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        menuAbout.add(menuInfo);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAddWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddWorkerActionPerformed
        DialogAddWorker work= new DialogAddWorker(this, rootPaneCheckingEnabled);
        work.setTitle("Add Worker");
        work.setVisible(true);
    }//GEN-LAST:event_menuAddWorkerActionPerformed

    private void menuAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddServiceActionPerformed
        DialogAddServei ser= new DialogAddServei(this, rootPaneCheckingEnabled);
        ser.setTitle("Add Service");
        ser.setVisible(true);
    }//GEN-LAST:event_menuAddServiceActionPerformed

    private void menuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoadActionPerformed
        try {
            this.control.carregarDades();
        } catch (IOException ex) {
            Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLoadActionPerformed

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        DialogInfo info= new DialogInfo(this, rootPaneCheckingEnabled);
        info.setTitle("About");
        info.setVisible(true);
    }//GEN-LAST:event_menuInfoActionPerformed

    private void menuEditWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditWorkerActionPerformed
        DialogEditWorker eWorker= new DialogEditWorker(this, rootPaneCheckingEnabled);
        eWorker.setTitle("Edit Client");
        eWorker.setVisible(true);
    }//GEN-LAST:event_menuEditWorkerActionPerformed

    private void menuEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditClientActionPerformed
        DialogEditClient eClient= new DialogEditClient(this, rootPaneCheckingEnabled);
        eClient.setTitle("Edit Client");
        eClient.setVisible(true);
    }//GEN-LAST:event_menuEditClientActionPerformed

    private void menuAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAddClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuItem menuAddClient;
    private javax.swing.JMenuItem menuAddService;
    private javax.swing.JMenuItem menuAddWorker;
    private javax.swing.JMenu menuClient;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem menuEditClient;
    private javax.swing.JMenuItem menuEditWorker;
    private javax.swing.JMenuItem menuInfo;
    private javax.swing.JMenuItem menuLoad;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenu menuService;
    private javax.swing.JMenu menuWorker;
    // End of variables declaration//GEN-END:variables
}
