/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Controlador;
import dades.CangurMenor;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marti Huerta Climent
 */
public class JMain extends javax.swing.JFrame {
    private Controlador control;
    
    private String[] llistaPrincipal;
    /**
     * Creates new form JMain
     */
    public JMain() {
        try {
            this.control.carregarDades();
        } catch (Exception ex) {
            Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.jLabel1.setVisible(false);
        this.jLabel2.setVisible(false);
        this.jLabel3.setVisible(false);
        this.jLabel4.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jLabel6.setVisible(false);
        this.jLabel7.setVisible(false);
        this.mostraLlista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        principalList = new javax.swing.JList<>();
        jTextNom = new javax.swing.JTextField();
        jTextPoblacio = new javax.swing.JTextField();
        jTextCognom = new javax.swing.JTextField();
        jTextAdreca = new javax.swing.JTextField();
        jTextNumero = new javax.swing.JTextField();
        jTextAval = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextNaixement = new javax.swing.JTextField();
        jButtonDesa = new javax.swing.JButton();
        jButtonCancela = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAddWorker = new javax.swing.JMenuItem();
        menuAddClient = new javax.swing.JMenuItem();
        menuAddService = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuSave = new javax.swing.JMenuItem();
        menuLoad = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cangurs");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Worker", "Client", "Service"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        principalList.setModel(null);
        jScrollPane1.setViewportView(principalList);

        jTextPoblacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPoblacioActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("City:");

        jLabel3.setText("Lastname:");

        jLabel4.setText("Adress:");

        jLabel5.setText("Phone Number:");

        jLabel6.setText("Guarantee:");

        jLabel7.setText("Birth Date:");

        jButtonDesa.setText("Desa");

        jButtonCancela.setText("Cancela");

        jMenu1.setText("File");

        menuAddWorker.setText("Add Worker");
        menuAddWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddWorkerActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddWorker);

        menuAddClient.setText("Add Client");
        menuAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddClientActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddClient);

        menuAddService.setText("Add Service");
        menuAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddServiceActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddService);

        jMenuBar1.add(jMenu1);

        menuEdit.setText("Edit");

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setText("Save");
        menuEdit.add(menuSave);

        menuLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuLoad.setText("Load");
        menuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoadActionPerformed(evt);
            }
        });
        menuEdit.add(menuLoad);

        jMenuBar1.add(menuEdit);

        menuAbout.setText("About");

        menuInfo.setText("Info");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        menuAbout.add(menuInfo);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextPoblacio)
                                        .addComponent(jTextNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextAval, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextCognom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextNaixement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonDesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancela))))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCognom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNaixement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDesa)
                            .addComponent(jButtonCancela))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoadActionPerformed
        try {
            this.control.carregarDades();
        } catch (IOException ex) {
            Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(JMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLoadActionPerformed

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        DialogInfo info= new DialogInfo(this, rootPaneCheckingEnabled);
        info.setTitle("About");
        info.setVisible(true);
    }//GEN-LAST:event_menuInfoActionPerformed

    private void menuAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddServiceActionPerformed
        DialogAddServei ser= new DialogAddServei(this, rootPaneCheckingEnabled);
        ser.setTitle("Add Service");
        ser.setVisible(true);
    }//GEN-LAST:event_menuAddServiceActionPerformed

    private void menuAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAddClientActionPerformed

    private void menuAddWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddWorkerActionPerformed
        DialogAddWorker work= new DialogAddWorker(this, rootPaneCheckingEnabled);
        work.setTitle("Add Worker");
        work.setVisible(true);
    }//GEN-LAST:event_menuAddWorkerActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        this.llista();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextPoblacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPoblacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPoblacioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancela;
    private javax.swing.JButton jButtonDesa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAdreca;
    private javax.swing.JTextField jTextAval;
    private javax.swing.JTextField jTextCognom;
    private javax.swing.JTextField jTextNaixement;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacio;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuItem menuAddClient;
    private javax.swing.JMenuItem menuAddService;
    private javax.swing.JMenuItem menuAddWorker;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem menuInfo;
    private javax.swing.JMenuItem menuLoad;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JList<String> principalList;
    // End of variables declaration//GEN-END:variables
public void mostraLlista(){
    if(this.jComboBox1.getSelectedItem().equals("Worker")){ 
        this.principalList.setListData(this.control.mostraCangur().toArray(this.llistaPrincipal=new String[this.control.mostraCangur().size()]));    
    }
    if(this.jComboBox1.getSelectedItem().equals("Client")){
        this.principalList.setListData(this.control.mostraClient().toArray(this.llistaPrincipal=new String[this.control.mostraClient().size()]));    
    }
    if(this.jComboBox1.getSelectedItem().equals("Service")){
    this.principalList.setListData(this.control.mostraService().toArray(this.llistaPrincipal=new String[this.control.mostraService().size()]));
    }
    this.llista();
}

    public void llista() {
        if(this.jComboBox1.getSelectedItem().equals("Worker")){
            this.jLabel1.setText("Name:");
            this.jLabel2.setText("Lastname:");
            this.jLabel3.setText("City:");
            this.jLabel4.setText("Adress:");
            this.jLabel5.setText("Phone Number:");
            this.jLabel6.setText("Guarantee:");
            this.jLabel7.setText("Birth Date:");
            //this.jTextNom.setText(this.control.getWorker(this.principalList.getSelectedIndex()).getName());
            this.jLabel1.setVisible(true);
            this.jLabel2.setVisible(true);
            this.jLabel3.setVisible(true);
            this.jLabel4.setVisible(true);
            this.jLabel5.setVisible(true);
            this.jLabel7.setVisible(true);
            if(this.control.getWorker(this.principalList.getSelectedIndex())instanceof CangurMenor){
                this.jLabel6.setVisible(true);
            }
            else{
                this.jLabel6.setVisible(false);
            }
        }
        if(this.jComboBox1.getSelectedItem().equals("Client")){
            this.jLabel1.setText("Name:");
            this.jLabel2.setText("Lastname:");
            this.jLabel3.setText("City:");
            this.jLabel4.setText("Adress:");
            this.jLabel5.setText("Phone Number:");
            this.jLabel1.setVisible(true);
            this.jLabel2.setVisible(true);
            this.jLabel3.setVisible(true);
            this.jLabel4.setVisible(true);
            this.jLabel5.setVisible(true);
            this.jLabel7.setVisible(false);
            this.jLabel6.setVisible(false);
        }
        if(this.jComboBox1.getSelectedItem().equals("Service")){
        
        }
    }


}
